apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill
  labels:
    app: bill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill
  template:
    metadata:
      labels:
        app: bill
    spec:
      containers:
        - name: bill
          image: "username/bill:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
